version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ssr:1.0
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
